version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea_production
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - GITEA__server__DOMAIN=${DOMAIN}
      - GITEA__server__ROOT_URL=https://${DOMAIN}/
      - GITEA__server__SSH_DOMAIN=${DOMAIN}
      - GITEA__server__SSH_PORT=2222
      - GITEA__server__SSH_LISTEN_PORT=22
      - GITEA__server__PROTOCOL=https
      - GITEA__server__CERT_FILE=/data/gitea/cert/cert.pem
      - GITEA__server__KEY_FILE=/data/gitea/cert/key.pem
    restart: always
    volumes:
      - ./gitea_data:/data
      - ./certs:/data/gitea/cert
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "443:3000"
      - "2222:22"
      - "80:80" # For HTTP to HTTPS redirection
    depends_on:
      - db
    networks:
      - gitea_network

  db:
    image: postgres:14
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - gitea_network

networks:
  gitea_network:
    driver: bridge
